language: minimal

script:
    - cd 3/
    - ./mdbook build
    - rm -rf mdbook*

deploy:
    provider: pages
    skip_cleaup: false
    github_token: $GIT_TOKEN
    keep_history: false
    committer_from_gh: true
    on:
        branch: master
