language: minimal

script:
    - cd 3/
    - wget https://github.com/Potla1995/Chuuko-demo-Koi-ga-Shitai/raw/master/mdbook
    - ./mdbook build
    - rm mdbook
    - git add .

deploy:
    provider: pages
    cleanup: false
    github_token: $GIT_TOKEN
    keep_history: false
    committer_from_gh: true
    on:
        branch: master
