language: minimal

script:
    - cd 3/
    - ./mdbook build
    - git add .
    - git commit -m "Built MDBook(s)."

deploy:
    provider: pages
    cleanup: false
    github_token: $GIT_TOKEN
    keep_history: false
    committer_from_gh: true
    on:
        branch: master
